import { Container } from 'typedi';
import { SequelizeUserRepository } from './infrastructure/db/repositories/SequelizeUserRepository';
import { SequelizePetRepository } from './infrastructure/db/repositories/SequelizePetRepository';
import { SequelizeHealthRecordRepository } from './infrastructure/db/repositories/SequelizeHealthRecordRepository';
import { SequelizeVetRepository } from './infrastructure/db/repositories/SequelizeVetRepository';
import { SequelizeReminderRepository } from './infrastructure/db/repositories/SequelizeReminderRepository';
import { SequelizeNoteRepository } from './infrastructure/db/repositories/SequelizeNoteRepository';
import { SequelizePetShareRepository } from './infrastructure/db/repositories/SequelizePetShareRepository';
import { SequelizePetOwnershipTransferRepository } from './infrastructure/db/repositories/SequelizePetOwnershipTransferRepository';
import { SequelizeWeightEntryRepository } from './infrastructure/db/repositories/SequelizeWeightEntryRepository';
import { SequelizePhotoRepository } from './infrastructure/db/repositories/SequelizePhotoRepository';
import { SequelizeUserLimitsRepository } from './infrastructure/db/repositories/SequelizeUserLimitsRepository';
import { SequelizeAdminStatsRepository } from './infrastructure/db/repositories/SequelizeAdminStatsRepository';
import { SequelizeOAuthAccountRepository } from './infrastructure/db/repositories/SequelizeOAuthAccountRepository';
import { NOTE_REPOSITORY } from './domain/note/NoteRepository';
import { PET_SHARE_REPOSITORY } from './domain/share/PetShareRepository';
import { PET_OWNERSHIP_TRANSFER_REPOSITORY } from './domain/transfer/PetOwnershipTransferRepository';
import { USER_REPOSITORY } from './domain/user/UserRepository';
import { PET_REPOSITORY } from './domain/pet/PetRepository';
import { HEALTH_RECORD_REPOSITORY } from './domain/health/HealthRecordRepository';
import { VET_REPOSITORY } from './domain/vet/VetRepository';
import { REMINDER_REPOSITORY } from './domain/reminder/ReminderRepository';
import { WEIGHT_ENTRY_REPOSITORY } from './domain/weight/WeightEntryRepository';
import { PHOTO_REPOSITORY } from './domain/photo/PhotoRepository';
import { USER_LIMITS_REPOSITORY } from './domain/user/UserLimitsRepository';
import { ADMIN_STATS_REPOSITORY } from './domain/admin/AdminStatsRepository';
import { OAUTH_ACCOUNT_REPOSITORY } from './domain/oauth/OAuthAccountRepository';

export function registerDependencies(): void {
  Container.set(USER_REPOSITORY, Container.get(SequelizeUserRepository));
  Container.set(PET_REPOSITORY, Container.get(SequelizePetRepository));
  Container.set(HEALTH_RECORD_REPOSITORY, Container.get(SequelizeHealthRecordRepository));
  Container.set(VET_REPOSITORY, Container.get(SequelizeVetRepository));
  Container.set(REMINDER_REPOSITORY, Container.get(SequelizeReminderRepository));
  Container.set(NOTE_REPOSITORY, Container.get(SequelizeNoteRepository));
  Container.set(PET_SHARE_REPOSITORY, Container.get(SequelizePetShareRepository));
  Container.set(PET_OWNERSHIP_TRANSFER_REPOSITORY, Container.get(SequelizePetOwnershipTransferRepository));
  Container.set(WEIGHT_ENTRY_REPOSITORY, Container.get(SequelizeWeightEntryRepository));
  Container.set(PHOTO_REPOSITORY, Container.get(SequelizePhotoRepository));
  Container.set(USER_LIMITS_REPOSITORY, Container.get(SequelizeUserLimitsRepository));
  Container.set(ADMIN_STATS_REPOSITORY, Container.get(SequelizeAdminStatsRepository));
  Container.set(OAUTH_ACCOUNT_REPOSITORY, Container.get(SequelizeOAuthAccountRepository));
}
